### ISSUE TITLE
a little suggestion

### ISSUE THREAD

**Issue by Bkm016** [abmcar/EasyVar#1]
在开发过程中我们通常应当遵守代码规范（[Google Style Guide (Java)](https://google.github.io/styleguide/javaguide.html) 或 [阿里巴巴 Java 开发手册](https://github.com/alibaba/p3c/blob/master/Java开发手册（嵩山版）.pdf)）。

这是不符合规范的错误写法：
<img width="250" alt="image" src="https://user-images.githubusercontent.com/27818531/129032793-b9f4c625-ea76-44ac-9371-d9d3779b9333.png">

---
错误的路径分隔符号：
https://github.com/abmcar/EasyVar/blob/b86a6af5482e8fb6db12fdd3653ebb255d694cf1/src/main/java/top/abmcar/easyvar/config/ConfigUtil.java#L32

应当使用正斜杠或是 `File.pathSeparatorChar`

---
不该出现的换行符号：
https://github.com/abmcar/EasyVar/blob/b86a6af5482e8fb6db12fdd3653ebb255d694cf1/src/main/java/top/abmcar/easyvar/commandListener/commandListener.java#L31

通过 Bukkit 方法向玩家或控制台发送的信息不需要换行符号，况且，
https://github.com/abmcar/EasyVar/blob/b86a6af5482e8fb6db12fdd3653ebb255d694cf1/src/main/java/top/abmcar/easyvar/messageSender/MessageSender.java#L25

你还在后面删掉了它。

---
在最新的 Idea 版本中，可以在 `Preferences` -> `Tools` -> `Actions on Save` 中开启 `Reformat code` 功能来在文件保存时自动格式化代码，让你的代码看起来更加美观。

<img width="400" alt="image" src="https://user-images.githubusercontent.com/27818531/129034396-295c7495-3de9-4a0a-9fe5-fdd1eb78543b.png">

---

如果你对插件开发工作感兴趣或是想与其他开发者共同交流进步，欢迎加入我们的交流群：809083692

**Comment by abmcar** [comment]
感谢您的建议！
已加群,希望能在交流群学到更多有用的开发知识。
